service: wallet

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128

iamRoleStatements:
  - Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
    Resource: "*"

  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  createCategory:
    handler: api/category.create
    events:
      - http:
          path: category/create
          method: post
          cors: true
  listCategories:
    handler: api/category.list
    events:
      - http:
          path: category/list
          method: get
          cors: true
  createRecord:
    handler: api/record.create
    events:
      - http:
          path: record/create
          method: post
          cors: true
  listRecords:
    handler: api/record.list
    events:
      - http:
          path: record/list
          method: get
          cors: true


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
