service: wallet

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  createCategory:
    handler: api/category.create
    events:
      - http:
          path: category/create
          method: post
          cors: true
  listCategories:
    handler: api/category.list
    events:
      - http:
          path: category/list
          method: get
          cors: true
  createRecord:
    handler: api/record.create
    events:
      - http:
          path: record/create
          method: post
          cors: true
  listRecords:
    handler: api/record.list
    events:
      - http:
          path: record/list
          method: get
          cors: true
  findRecord:
    handler: api/record.find
    events:
      - http:
          path: record/find
          method: post
          cors: true
  modifyRecord:
    handler: api/record.modify
    events:
      - http:
          path: record/modify
          method: post
          cors: true
  deleteRecord:
    handler: api/record.deleteRecord
    events:
      - http:
          path: record/delete
          method: post
          cors: true


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
